CREATE TABLE usuarios (
  codigo CHAR(8) PRIMARY KEY,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE categorias (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL UNIQUE,
  descricao TEXT
);

CREATE TABLE denuncias (
  id SERIAL PRIMARY KEY,
  usuario_codigo CHAR(8) NOT NULL REFERENCES usuarios(codigo),
  categoria_id INTEGER NOT NULL REFERENCES categorias(id),
  data_ocorrencia DATE NOT NULL CHECK (data_ocorrencia >= '1990-01-01'),
  estado VARCHAR(100) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  endereco VARCHAR(100) NOT NULL,
  descricao TEXT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pendente',
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO usuarios (codigo) VALUES
('ABC12345'),
('XYZ67890'),
('LMN11223'),
('QWE44556'),
('RTY77889'),
('UIO99001'),
('PAS22334'),
('DEF54321'),
('GHI98765'),
('JKL56789'),
('MNO23456'),
('PQR67890'),
('STU12345'),
('VWX89012'),
('YZA34567'),
('BCD78901'),
('EFG45678'),
('HIJ90123'),
('KLM56789'),
('NOP01234'),
('QRS67890'),
('TUV12345'),
('WXY78901'),
('ZAB34567'),
('CDE89012'),
('FGH45678'),
('IJK90123');

INSERT INTO categorias (nome, descricao) VALUES
('corrupcao', 'Corrupção'),
('abuso_poder', 'Abuso de poder'),
('fraude', 'Fraude'),
('discriminacao', 'Discriminação'),
('violacao_ambiental', 'Violação ambiental'),
('violencia', 'Violência'),
('peculato', 'Peculato'),
('nepotismo', 'Nepotismo'),
('desvio_dinheiro', 'Desvio de dinheiro público'),
('falsa_identidade', 'Falsidade de identidade'),
('extorsao', 'Extorsão'),
('suborno', 'Suborno'),
('falsificacao', 'Falsificação de documentos'),
('assedio', 'Assédio moral ou sexual'),
('evasao_fiscal', 'Evasão fiscal');

INSERT INTO denuncias (usuario_codigo, categoria_id, data_ocorrencia, estado, cidade, endereco, descricao, status)
VALUES
 ('ABC12345', 1, '2023-10-01', 'São Paulo', 'São Paulo', 'Rua das Flores, 123 - Centro Histórico - São Paulo - SP', 'Foi identificado um possível esquema de corrupção envolvendo servidores públicos responsáveis por contratos administrativos, onde há indícios de favorecimento indevido, recebimento de vantagens ilícitas e manipulação de processos internos para benefício próprio.', 'pendente'),
('XYZ67890', 2, '2023-09-15', 'Rio de Janeiro', 'Rio de Janeiro', 'Avenida Atlântica, 456 - Copacabana - Rio de Janeiro - RJ', 'Relato de abuso de poder por parte de autoridade pública que utilizou sua posição para intimidar cidadãos, impondo decisões arbitrárias e desrespeitando normas legais estabelecidas, causando prejuízos e constrangimento às vítimas envolvidas.', 'em_andamento'),
('LMN11223', 3, '2024-01-10', 'Paraná', 'Curitiba', 'Rua XV de Novembro, 1000 - Centro Comercial - Curitiba - PR', 'Há suspeitas consistentes de fraude em processo licitatório, com possível combinação prévia entre empresas participantes, manipulação de documentos oficiais e direcionamento do resultado final para favorecer determinados grupos econômicos.', 'pendente'),
('QWE44556', 4, '2024-02-05', 'Bahia', 'Salvador', 'Avenida Sete de Setembro, 250 - Centro Histórico - Salvador - BA', 'Foi relatado um caso de discriminação dentro de um órgão público, onde indivíduos foram tratados de maneira desigual com base em características pessoais, resultando em constrangimento, exclusão e prejuízo no acesso a serviços essenciais.', 'em_andamento'),
('RTY77889', 6, '2024-03-12', 'Minas Gerais', 'Belo Horizonte', 'Rua da Bahia, 300 - Região Central - Belo Horizonte - MG', 'Denúncia envolvendo situação de violência praticada por agente público durante abordagem, incluindo uso excessivo de força, ameaças verbais e comportamento inadequado que coloca em risco a integridade física e psicológica dos envolvidos.', 'pendente'),
('UIO99001', 5, '2024-03-20', 'Amazonas', 'Manaus', 'Avenida Eduardo Ribeiro, 700 - Centro - Manaus - AM', 'Foi identificada possível violação ambiental em área protegida, com indícios de desmatamento irregular, descarte inadequado de resíduos e ausência de fiscalização adequada por parte dos órgãos responsáveis pela preservação ambiental.', 'em_andamento'),
('PAS22334', 8, '2024-04-01', 'Rio Grande do Sul', 'Porto Alegre', 'Rua dos Andradas, 450 - Centro Histórico - Porto Alegre - RS', 'Há indícios de prática de nepotismo dentro da administração pública, com nomeações de familiares para cargos estratégicos sem critérios técnicos, comprometendo a transparência, eficiência e legalidade das decisões administrativas.', 'pendente'),
('ABC12345', 9, '2024-04-10', 'São Paulo', 'Campinas', 'Avenida Brasil, 1200 - Bairro Guanabara - Campinas - SP', 'Foram identificados indícios de desvio de dinheiro público em obra municipal, com possíveis superfaturamentos, medições falsas e ausência de execução real de serviços contratados, causando prejuízo significativo aos cofres públicos.', 'em_andamento'),
('XYZ67890', 10, '2024-04-15', 'Ceará', 'Fortaleza', 'Avenida Beira Mar, 900 - Meireles - Fortaleza - CE', 'Relato de utilização de falsa identidade para obtenção de benefícios indevidos junto a programas governamentais, incluindo apresentação de documentos falsificados e tentativa de enganar sistemas de verificação oficial.', 'pendente'),
('LMN11223', 11, '2024-04-20', 'Pernambuco', 'Recife', 'Rua do Bom Jesus, 200 - Recife Antigo - Recife - PE', 'Denúncia aponta tentativa de extorsão envolvendo servidor público que teria exigido vantagens financeiras indevidas para facilitar processos administrativos, utilizando sua posição para pressionar e intimidar cidadãos.', 'em_andamento'),
('QWE44556', 12, '2024-04-25', 'Goiás', 'Goiânia', 'Avenida Goiás, 1500 - Setor Central - Goiânia - GO', 'Foi identificado possível pagamento de suborno com o objetivo de acelerar processos internos em órgão público, indicando quebra de integridade administrativa e favorecimento indevido mediante vantagens ilícitas.', 'pendente'),
('RTY77889', 13, '2024-05-01', 'Santa Catarina', 'Florianópolis', 'Avenida Beira-Mar Norte, 300 - Centro - Florianópolis - SC', 'Há evidências de falsificação de documentos oficiais, incluindo adulteração de registros e emissão de certificados fraudulentos, com potencial impacto jurídico e administrativo significativo para as instituições envolvidas.', 'em_andamento'),
('DEF54321', 1, '2024-05-05', 'São Paulo', 'Santos', 'Rua Amaro Martins, 789 - Centro - Santos - SP', 'Suspeitas de corrupção em concessões de serviços públicos municipais, com possível favorecimento de determinada empresa em detrimento de outras concorrentes, violando princípios de transparência e isonomia.', 'resolvido'),
('GHI98765', 7, '2024-05-10', 'Espírito Santo', 'Vitória', 'Avenida Getúlio Vargas, 456 - Centro - Vitória - ES', 'Relato de peculato envolvendo servidor público que teria desviado bens e recursos públicos para uso pessoal, causando danos ao erário e comprometendo a probidade administrativa.', 'em_andamento'),
('JKL56789', 2, '2024-05-12', 'Distrito Federal', 'Brasília', 'SCLN 202 Bloco B, 50 - Asa Norte - Brasília - DF', 'Denúncia de abuso de autoridade por magistrado que teria proferido sentenças arbitrárias e persecutórias contra determinadas partes processuais sem fundamentação jurídica adequada.', 'pendente'),
('MNO23456', 3, '2024-05-15', 'Mato Grosso do Sul', 'Campo Grande', 'Rua Dom Aquino, 2000 - Centro - Campo Grande - MS', 'Indícios de fraude no sistema de licitações públicas, com participação de empresas de fachada e manipulação de editais para garantir contratação pré-determinada.', 'resolvido'),
('PQR67890', 4, '2024-05-18', 'Rondônia', 'Porto Velho', 'Avenida 7 de Setembro, 1500 - Centro - Porto Velho - RO', 'Relato de discriminação racial em instituição pública, onde candidatos de determinada cor foram submetidos a tratamento diferenciado durante processos de seleção.', 'em_andamento'),
('STU12345', 5, '2024-05-20', 'Tocantins', 'Palmas', 'Quadra AENO, Conjunto 19, Lote 1 - Centro - Palmas - TO', 'Denúncia de violação ambiental em licenciamento de obra pública, com possível impacto não avaliado adequadamente em estudos de impacto ambiental.', 'pendente'),
('VWX89012', 6, '2024-05-22', 'Maranhão', 'São Luís', 'Avenida Getúlio Vargas, 1000 - Centro - São Luís - MA', 'Relato de violência policial durante abordagem em comunidade carente, com aplicação de força desproporcional e agressão a cidadãos desarmados.', 'em_andamento'),
('YZA34567', 14, '2024-05-25', 'Piauí', 'Teresina', 'Rua Magalhães Filho, 800 - Centro - Teresina - PI', 'Denúncia de assédio moral e sexual em ambiente de trabalho público, com omissão de supervisores na apuração de denúncias anteriores.', 'resolvido'),
('BCD78901', 15, '2024-05-28', 'Alagoas', 'Maceió', 'Avenida Fernandes Lima, 1200 - Centro - Maceió - AL', 'Indícios de evasão fiscal envolvendo empresas com contratos com órgão público, com possível lavagem de dinheiro através de operações fraudulentas.', 'pendente'),
('EFG45678', 8, '2024-06-01', 'Sergipe', 'Aracaju', 'Rua Santa Cruz, 500 - Centro - Aracaju - SE', 'Relato de nepotismo em contratação de pessoal para cargo público, com nomeação de parentes de servidor responsável pela seleção.', 'em_andamento'),
('HIJ90123', 9, '2024-06-03', 'Paraíba', 'João Pessoa', 'Avenida Getúlio Vargas, 2000 - Centro - João Pessoa - PB', 'Denúncia de desvio de recursos públicos destinados a programas sociais, com possível enriquecimento ilícito de gestores responsáveis.', 'pendente'),
('KLM56789', 10, '2024-06-05', 'Rio Grande do Norte', 'Natal', 'Avenida Hermes da Fonseca, 1500 - Centro - Natal - RN', 'Indícios de fraude em benefícios previdenciários, com pessoas utilizando identidades falsas para receber valores indevidos.', 'resolvido'),
('NOP01234', 11, '2024-06-08', 'Acre', 'Rio Branco', 'Avenida Getúlio Vargas, 900 - Centro - Rio Branco - AC', 'Relato de extorsão contra empresas que atuam na região, com cobrança de valores indevidos por agentes públicos para permitir operações.', 'em_andamento'),
('QRS67890', 12, '2024-06-10', 'Amapá', 'Macapá', 'Avenida Fabio Rego, 1000 - Centro - Macapá - AP', 'Denúncia de suborno em processos administrativos, com servidores públicos exigindo vantagens para expedir documentos necessários.', 'pendente'),
('TUV12345', 13, '2024-06-12', 'Roraima', 'Boa Vista', 'Avenida Getúlio Vargas, 2500 - Centro - Boa Vista - RR', 'Indícios de falsificação de documentos em registros públicos, incluindo alteração de dados de servidores para simular tempo de serviço.', 'em_andamento'),
('WXY78901', 1, '2024-06-15', 'Minas Gerais', 'Montes Claros', 'Avenida Cula Mangabeira, 1200 - Centro - Montes Claros - MG', 'Suspeitas de esquema de corrupção envolvendo licitação de obras de infraestrutura, com propinas a agentes públicos.', 'resolvido'),
('ZAB34567', 2, '2024-06-17', 'São Paulo', 'Sorocaba', 'Rua Dom Pedro II, 800 - Centro - Sorocaba - SP', 'Relato de abuso de poder por delegado que teria realizado prisões arbitrárias sem fundamentação legal adequada.', 'pendente'),
('CDE89012', 3, '2024-06-20', 'Rio de Janeiro', 'Niterói', 'Rua General Osório, 500 - Centro - Niterói - RJ', 'Denúncia de fraude em auditoria pública, com manipulação de documentos para ocultar desvios de recursos.', 'em_andamento'),
('FGH45678', 4, '2024-06-22', 'Bahia', 'Feira de Santana', 'Avenida Getúlio Vargas, 1500 - Centro - Feira de Santana - BA', 'Indícios de discriminação de gênero em seleção pública, com preferência indevida por candidatos masculinos.', 'pendente'),
('IJK90123', 5, '2024-06-25', 'Paraná', 'Londrina', 'Avenida Getúlio Vargas, 2000 - Centro - Londrina - PR', 'Relato de violação de direitos ambientais em licenciamento de obra, com descarte inadequado de resíduos em Rio.', 'resolvido'),
('ABC12345', 6, '2024-06-27', 'Santa Catarina', 'Blumenau', 'Rua XV de Novembro, 1000 - Centro - Blumenau - SC', 'Denúncia de violência em abordagem policial, com uso de armas de fogo contra cidadão desarmado.', 'em_andamento'),
('XYZ67890', 14, '2024-07-01', 'Rio Grande do Sul', 'Pelotas', 'Rua Félix da Cunha, 600 - Centro - Pelotas - RS', 'Relato de assédio sexual por supervisor em órgão público estadual, com vítima sendo coagida a rescindir contrato.', 'pendente'),
('LMN11223', 15, '2024-07-03', 'Espírito Santo', 'Cariacica', 'Avenida Centroamericana, 1000 - Centro - Cariacica - ES', 'Indícios de evasão fiscal em operações comerciais com a administração pública.', 'resolvido'),
('QWE44556', 1, '2024-07-05', 'Mato Grosso', 'Cuiabá', 'Avenida Getúlio Vargas, 3000 - Centro - Cuiabá - MT', 'Denúncia de uso indevido de dados pessoais por servidor público para fins políticos.', 'em_andamento'),
('RTY77889', 1, '2024-07-08', 'Distrito Federal', 'Brasília', 'SCLS Quadra 107 Bloco C - Asa Sul - Brasília - DF', 'Relato de corrupção em concessão de alugueis públicos, com favorecimento de proprietários aliados.', 'pendente'),
('UIO99001', 7, '2024-07-10', 'Ceará', 'Caucaia', 'Rua Vicente Sousa, 900 - Centro - Caucaia - CE', 'Denúncia de peculato envolvendo gestor de fundo público que desviou recursos para conta pessoal.', 'em_andamento'),
('PAS22334', 2, '2024-07-12', 'Pernambuco', 'Jaboatão dos Guararapes', 'Avenida Getúlio Vargas, 2200 - Centro - Jaboatão dos Guararapes - PE', 'Relato de abuso de autoridade por juiz que teria condenado cidadão sem permitir direito de defesa adequado.', 'resolvido'),
('DEF54321', 3, '2024-07-15', 'Paraíba', 'Campina Grande', 'Rua Maciel Pinheiro, 800 - Centro - Campina Grande - PB', 'Indícios de fraude em processo de concessão de serviço público municipal.', 'pendente'),
('GHI98765', 4, '2024-07-17', 'Piauí', 'Parnaíba', 'Avenida Getúlio Vargas, 1800 - Centro - Parnaíba - PI', 'Relato de discriminação de deficientes em acesso a programas de assistência social.', 'em_andamento'),
('JKL56789', 5, '2024-07-20', 'Maranhão', 'Imperatriz', 'Avenida Getúlio Vargas, 2500 - Centro - Imperatriz - MA', 'Denúncia de impacto ambiental não mitigado em obra de infraestrutura pública.', 'pendente'),
('MNO23456', 6, '2024-07-22', 'Alagoas', 'Rio Largo', 'Rua João Pessoa, 500 - Centro - Rio Largo - AL', 'Relato de abuso de autoridade policial durante fiscalização em estabelecimento comercial.', 'resolvido'),
('PQR67890', 14, '2024-07-25', 'Sergipe', 'Nossa Senhora do Socorro', 'Avenida Getúlio Vargas, 1500 - Centro - Nossa Senhora do Socorro - SE', 'Denúncia de assédio moral contra servidora pública por gerente direto.', 'em_andamento'),
('STU12345', 15, '2024-07-27', 'Tocantins', 'Araguaína', 'Avenida Getúlio Vargas, 3000 - Centro - Araguaína - TO', 'Indícios de fraude em licitação para fornecimento de materiais de saúde pública.', 'pendente'),
('VWX89012', 1, '2024-08-01', 'Amazonas', 'Itacoatiara', 'Rua Getúlio Vargas, 700 - Centro - Itacoatiara - AM', 'Relato de violação de propriedade intelectual por órgão público.', 'resolvido'),
('YZA34567', 1, '2024-08-03', 'Rondônia', 'Ariquemes', 'Avenida Getúlio Vargas, 1200 - Centro - Ariquemes - RO', 'Denúncia de corrupção em distribuição de verbas municipais para escolas.', 'em_andamento'),
('BCD78901', 7, '2024-08-05', 'Acre', 'Cruzeiro do Sul', 'Rua Getúlio Vargas, 600 - Centro - Cruzeiro do Sul - AC', 'Relato de peculato em fundo de pensão de servidores públicos estaduais.', 'pendente'),
('EFG45678', 2, '2024-08-08', 'Amapá', 'Oiapoque', 'Avenida Getúlio Vargas, 400 - Centro - Oiapoque - AP', 'Denúncia de abuso de poder por prefeito que teria perseguido opositores políticos.', 'resolvido'),
('HIJ90123', 3, '2024-08-10', 'Roraima', 'Rorainópolis', 'Avenida Getúlio Vargas, 900 - Centro - Rorainópolis - RR', 'Indícios de fraude em programa de transferência de renda governamental.', 'em_andamento');
